name: golangci-lint
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get

      - name: GolangCI-Lint
        run:  |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | \
          sh -s -- -b $(go env GOPATH)/bin v1.24.0 && \
          $(go env GOPATH)/bin/golangci-lint \
          run --enable=golint --disable=deadcode,unused ./...
